In [3]:
import numpy as np
import pandas as pd

In [5]:
data=pd.read_csv("taxi.csv")

In [6]:
data

Priceperweek  Population  Monthlyincome  Averageparkingpermonth  \
0             15     1800000           5800                      50   
1             15     1790000           6200                      50   
2             15     1780000           6400                      60   
3             25     1778000           6500                      60   
4             25     1750000           6550                      60   
5             25     1740000           6580                      70   
6             25     1725000           8200                      75   
7             30     1725000           8600                      75   
8             30     1720000           8800                      75   
9             30     1705000           9200                      80   
10            30     1710000           9630                      80   
11            40     1700000          10570                      80   
12            40     1695000          11330                      85   
13            40     1695000          11600                     100   
14            40     1690000          11800                     105   
15            40     1630000          11830                     105   
16            65     1640000          12650                     105   
17           102     1635000          13000                     110   
18            75     1630000          13224                     125   
19            75     1620000          13766                     130   
20            75     1615000          14010                     150   
21            80     1605000          14468                     155   
22            86     1590000          15000                     165   
23            98     1595000          15200                     175   
24            87     1590000          15600                     175   
25            77     1600000          16000                     190   
26            63     1610000          16200                     200   

    Numberofweeklyriders  
0                 192000  
1                 190400  
2                 191200  
3                 177600  
4                 176800  
5                 178400  
6                 180800  
7                 175200  
8                 174400  
9                 173920  
10                172800  
11                163200  
12                161600  
13                161600  
14                160800  
15                159200  
16                148800  
17                115696  
18                147200  
19                150400  
20                152000  
21                136000  
22                126240  
23                123888  
24                126080  
25                151680  
26                152800

In [19]:
import pickle
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [9]:
data_x=data.iloc[:,0:-1].values
data_y=data.iloc[:,-1].values

In [12]:
data_y

array([192000, 190400, 191200, 177600, 176800, 178400, 180800, 175200,
       174400, 173920, 172800, 163200, 161600, 161600, 160800, 159200,
       148800, 115696, 147200, 150400, 152000, 136000, 126240, 123888,
       126080, 151680, 152800], dtype=int64)

In [14]:
x_train,x_test,y_train,y_test=train_test_split(data_x,data_y,test_size=0.3,random_state=0)

In [18]:
y_train

array([152000, 148800, 190400, 172800, 152800, 151680, 174400, 180800,
       176800, 147200, 173920, 175200, 126240, 177600, 192000, 136000,
       159200, 161600], dtype=int64)

In [21]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
reg.score(x_test,y_test)

0.9157379222488224

In [23]:
reg.score(x_train,y_train)

0.9428364724316814

In [24]:
pickle.dump(reg,open('taxi.pkl','wb')) # create model name taxi.pkl

In [25]:
model=pickle.load(open('taxi.pkl','rb'))

In [27]:
model.predict([[80,1770000,6000,85]])

array([153448.45038985])